### ISSUE TITLE
0.3.1 Release?

### ISSUE THREAD

**Issue by llchan** [Jupyter-contrib/jupyter_contrib_core#4]
Can we ship a 0.3.1 release with the MANIFEST.in character fix so that this installs in python3?

**Comment by jcb91** [comment]
Sure, I'm happy to release, but I'm not quite sure what the fix you're proposing is? Feel free to submit PR!

**Comment by llchan** [comment]
It's already fixed in a46a2ff0db815c647bebed784dbff81f6f553c41, just not cut into a release. So should be pretty straightforward :)

**Comment by jcb91** [comment]
Oh, ok! I'd forgotten about that (obviously). Yeah, I'll roll this into a patch release hopefully tonight or tomorrow...

**Comment by jcb91** [comment]
Ok, 0.3.1 is now available as a [git tag](https://github.com/Jupyter-contrib/jupyter_contrib_core/releases/0.3.1) here, [from pypi](https://pypi.org/project/jupyter_contrib_core/0.3.1/) & [from conda-forge](https://anaconda.org/conda-forge/jupyter_contrib_core/files?version=0.3.1)
